package report

import (
	"html/template"
	"io"
	"time"

	"github.com/ergonix/auditor/backend/internal/models"
)

// HTMLExporter renders a standalone, styled HTML report (no external assets).
type HTMLExporter struct{}

func (HTMLExporter) ContentType() string { return "text/html; charset=utf-8" }
func (HTMLExporter) Ext() string         { return "html" }

type htmlData struct {
	FA          *FullAudit
	GeneratedAt string
	Severities  []models.Severity
	SevCount    map[models.Severity]int
}

func (HTMLExporter) Export(w io.Writer, fa *FullAudit) error {
	data := htmlData{
		FA:          fa,
		GeneratedAt: time.Now().Format("2006-01-02 15:04 MST"),
		Severities: []models.Severity{
			models.SeverityCritical, models.SeverityHigh,
			models.SeverityMedium, models.SeverityLow,
		},
		SevCount: fa.Audit.Stats.BySeverity,
	}
	return htmlTmpl.Execute(w, data)
}

var htmlTmpl = template.Must(template.New("report").Funcs(template.FuncMap{
	"fmtMs": func(ms int64) string {
		return time.Duration(ms * int64(time.Millisecond)).Round(time.Second).String()
	},
	"pct": func(conf float64) int { return int(conf * 100) },
}).Parse(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Audit #{{.FA.Audit.ID}} — Ergonix Website Audit Report</title>
<style>
  :root { --critical:#dc2626; --high:#ea580c; --medium:#d97706; --low:#65a30d; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Roboto, Arial, sans-serif; margin: 0;
         background:#f6f7f9; color:#1f2937; }
  .wrap { max-width: 1100px; margin: 0 auto; padding: 32px 20px 64px; }
  header { border-bottom: 3px solid #111827; padding-bottom: 16px; margin-bottom: 24px; }
  h1 { margin: 0 0 4px; font-size: 26px; }
  .muted { color:#6b7280; font-size: 13px; }
  .cards { display:flex; flex-wrap:wrap; gap:12px; margin: 20px 0 28px; }
  .card { background:#fff; border:1px solid #e5e7eb; border-radius:10px; padding:14px 20px; min-width:130px; }
  .card b { display:block; font-size:24px; }
  .card span { font-size:12px; color:#6b7280; text-transform:uppercase; letter-spacing:.04em; }
  .sev { display:inline-block; padding:2px 10px; border-radius:999px; color:#fff; font-size:11px;
         font-weight:600; text-transform:uppercase; letter-spacing:.03em; }
  .sev.critical{background:var(--critical)} .sev.high{background:var(--high)}
  .sev.medium{background:var(--medium)} .sev.low{background:var(--low)}
  table { width:100%; border-collapse:collapse; background:#fff; border:1px solid #e5e7eb;
          border-radius:10px; overflow:hidden; font-size: 13px; }
  th { text-align:left; background:#111827; color:#f9fafb; padding:9px 12px; font-size:11px;
       text-transform:uppercase; letter-spacing:.05em; }
  td { padding:10px 12px; border-top:1px solid #f0f1f3; vertical-align: top; }
  tr:hover td { background:#f9fafb; }
  .url { font-family: ui-monospace, Consolas, monospace; font-size:11px; color:#2563eb;
         word-break: break-all; }
  h2 { margin: 36px 0 12px; font-size: 18px; }
  .sites td:first-child { font-weight: 600; }
  footer { margin-top: 40px; font-size: 12px; color:#9ca3af; }
</style>
</head>
<body>
<div class="wrap">
<header>
  <h1>Ergonix Website Audit — Report #{{.FA.Audit.ID}}</h1>
  <div class="muted">Status: {{.FA.Audit.Status}} · Created {{.FA.Audit.CreatedAt.Format "2006-01-02 15:04"}} · Generated {{.GeneratedAt}}</div>
</header>

<div class="cards">
  <div class="card"><b>{{.FA.Audit.Stats.TotalWebsites}}</b><span>Websites</span></div>
  <div class="card"><b>{{.FA.Audit.Stats.TotalPages}}</b><span>Pages scanned</span></div>
  <div class="card"><b>{{.FA.Audit.Stats.TotalIssues}}</b><span>Issues</span></div>
  <div class="card"><b>{{fmtMs .FA.Audit.Stats.DurationMs}}</b><span>Duration</span></div>
  {{range .Severities}}<div class="card"><b>{{index $.SevCount .}}</b><span>{{.}}</span></div>{{end}}
</div>

<h2>Websites</h2>
<table class="sites">
  <tr><th>Website</th><th>Status</th><th>Pages</th><th>Issues</th><th>Duration</th><th>Note</th></tr>
  {{range .FA.Audit.Sites}}
  <tr><td>{{.Website}}</td><td>{{.Status}}</td><td>{{.PagesCrawled}}</td><td>{{.IssueCount}}</td>
      <td>{{fmtMs .DurationMs}}</td><td class="muted">{{.Error}}</td></tr>
  {{end}}
</table>

<h2>Issues ({{len .FA.Issues}})</h2>
<table>
  <tr><th>Severity</th><th>Website</th><th>Category</th><th>Source</th><th>Page</th>
      <th>Description</th><th>Suggested fix</th><th>Conf.</th></tr>
  {{range .FA.Issues}}
  <tr>
    <td><span class="sev {{.Severity}}">{{.Severity}}</span></td>
    <td>{{.Website}}</td>
    <td>{{.Category}}</td>
    <td>{{.Source}}</td>
    <td class="url">{{.PageURL}}</td>
    <td><b>{{.Title}}</b><br>{{.Description}}</td>
    <td>{{.SuggestedFix}}</td>
    <td>{{pct .Confidence}}%</td>
  </tr>
  {{end}}
</table>

<footer>Generated by the Ergonix Website Audit Platform.</footer>
</div>
</body>
</html>
`))
